=encoding utf8

=head1 Ffc

Schnelle, leichtgewichtige, übersichtliche, schlanke und 
unkomplizierte Foren- und Nachrichtenplattform für eine 
überschaubare Anzahl von händisch angelegten angemeldeten 
Teilnehmern mit klarer und einfacher Datenhaltung und 
simpler technischer Struktur.  

=head2 Features

=over 4

=item Einfache Bedienung

=item Schlanke Präsentation

=item Ressourcenschohnende Darbietung

=item Einfache klare Datenhaltung

=item Alle Daten werden grundlegend in einer zentralen Tabelle erfasst

=item Kein unnützer Ballast wie 

=over 8

=item Beitragstitel

=item Überbordender Eyecandy

=item Featuritis

=item Avatare (ja, die sind rausgefallen)

=back

=item Datenaustauschplattform für alle Teilbereiche

=item Teilbereiche:

=over 8

=item Diskussionsforum mit Kategorien

=item Nachrichtenplattform für Privatnachrichten an einzelne Teilnehmer

=item Notizen für den eigenen Bedarf

=back

=back

=head2 Ideen für später mal

=head3 Remote-Kategorien

Kategorien zum Verbinden mehrerer Instanzen dieser Software auf 
verschiedenen Systemen im Internet verteilt, die sich automatisch
inhaltlich abgleichen für eine dezentrale forenübergreifende
Kommunikation.

=over 4

=item Wichtig ist hier an erster Stelle, eine robuste ausfallsichere Austauschplattform zu schaffen

=item Die Software liefert eine REST-Schnittstelle hinter der, über eine Anmeldung, Daten ausgetauscht werden können zu spezifischen Kategorien

=item Kategorien bekommen diese REST-URL der jeweilig anderen Instanz hinterlegt (zusätzlich zu den Anmeldedaten, denn ohne Anmeldung läuft nichts)

=item Über einen cron-Job erfolgt der Datenabgleich

=item Wenn benutzer in der entsprechenden Remote-Kategorie (spezielle Kennzeichnung!!!) etwas posten, wird das zeitversetzt an die entsprechende anderen Instanz übertragen und umgekehrt

=back

=head2 Datenstruktur

Alles ist ein Beitrag.

Beiträge haben einen Text, ein Erstelldatum und einen Urheber.

Beiträge ohne Zielperson (C<to>) gelten als öffentliche Forenbeiträge.
Beiträge mit anderer Zielperson, als der Urheber ist, gelten als 
Privatnachrichten. Beiträge mit dem Urheber zusätzlich als Zielperson
gelten als eigene Notizen.

Bei Bedarf werden an die Beiträge aus dem Forum über eine Extratabelle
Kategorien angefügt. Wird das Kategoriefeld leer gelassen, gelten die
Beiträge als allgemeine Beiträge.

Benutzer können nur von bestehenden Administratorbenutzern hinzugefügt
werden, können ihr Passwort und ihre Emailadresse aber selber ändern.

Jedem Beitrag kann genau eine Datei angehängt werden ("Zwang" zur 
Archivierung und Komprimierung). Diese Datei wird dann über einen
Beitragsindex referenziert im Dateisystem abgelegt und kann entsprechend
von allen oder von den Zielpersonen des Beitrages abgerufen werden.

=cut
