#!/usr/bin/env perl

use 5.016;
use strict;
use warnings;

use File::Spec::Functions qw(catfile splitdir);
use File::Basename;
use lib catfile splitdir(File::Basename::basename(__FILE__)), '..', 'lib';

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Ffc');
