#!/usr/bin/env perl

use 5.18.0;
use strict;
use warnings;

use File::Spec::Functions qw(catdir splitdir);
use File::Basename;
use lib catdir(splitdir(File::Basename::dirname(__FILE__)), '..', 'lib');

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Ffc');
